services:
  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5433:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cortexsys_todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11111111
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cortexsys_todo"]
      interval: 5s
      retries: 10
      timeout: 10s

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: django-insecure-05qnasgfesfw1*zhftdfxwtb1*c9ex80a1u#6+914a%ws&+(q4l!5k
      DEBUG: True
      POSTGRES_HOST: db
      ALLOWED_HOSTS: '*'
    command: >
      sh -c "python3 ./cortexsys_todo/manage.py migrate &&
      python3 ./cortexsys_todo/manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres_data:
    