# Generated by Django 5.2.5 on 2025-08-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("pending", "pending"), ("completed", "completed")],
                default="pending",
                max_length=15,
            ),
        ),
    ]
