# Generated by Django 5.2.5 on 2025-09-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "low"), ("medium", "medium"), ("high", "high")],
                default="medium",
                max_length=50,
            ),
        ),
    ]
